### PR TITLE
Now able to access bookmarks

### PR DESCRIPTION
**Pull request by ItzAfroBoy**

### CODE REVIEW

**Review by Nimplex — COMMENTED** [review]
It looks good.

**Review by Nimplex — CHANGES_REQUESTED** [review]
You'r code is causing error.

image

**Review by Nimplex — APPROVED** [review]
Everything works good, (you must to install this as extension before trying to use bookmarks).

**Comment by yrwq** [comment]
As mentioned before, this requires installing termstart as an extension, which is not satisfies the main goal of termstart: portability.

**Comment by ItzAfroBoy** [comment]
Thanks for the feedback, I appreciate the comments. I am now working on trying to get the bookmarks without having termstart as an extension

**Comment by yrwq** [comment]
According to my knowledge, bookmarks are not accessible using plain javascript. The only way is to install termstart as an extension.

**Comment by yrwq** [comment]
I will make a branch for this.
Closing this request

**Pull request closed without merging**
